### Numpy, Pandas, Matploblip nâng cao

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
print(x)

[1 2 3 4 5 6 7]


In [ ]:
data = [(1,2),(3,4),(5,6)]
mang = np.array(data)
print(mang)
print(mang[1,1])
print(mang[-1,1])
print(mang[-2,1])
print(mang[(1,2),:])
print(mang[1:3])
print(mang[0])
print(mang[:,0])
print(mang[0:2,0])
print(mang[(0,2),0])

[[1 2]
 [3 4]
 [5 6]]
4
6
4
[[3 4]
 [5 6]]
[[3 4]
 [5 6]]
[1 2]
[1 3 5]
[1 3]
[1 5]


In [ ]:
## start, end, step
print(mang[::2,0])

[1 5]


In [ ]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
mang = np.array(x)
print(mang)
print(mang[::,1]) ##2 6 10 14
print(mang[1:3,2]) ## 7 11
print(mang[[0,1,2],[3,2,1]])  ## 4 7 10
print(mang[3,::-1])   ## 16 15 14 13

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2  6 10 14]
[ 7 11]
[ 4  7 10]
[16 15 14 13]


In [ ]:
x = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
mang = np.array(x)
print(mang)

##lấy 4 5 6
print(mang[1])
##lấy 2 5
print(mang[:2,1])
##lấy 3 4
print(mang[[0,1],[2,0]])
##lấy 9 6 3
print(mang[::-1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[2 5]
[3 4]
[9 6 3]


In [ ]:
x = [
    1,2,3,4,5,6,7,8,9,10
]
chan = [ num for num in x if num % 2 ==0 ]
print(x)
print(chan)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10]


In [ ]:
x = np.ones((1,3,3))
print(x)

x1 = np.arange(3)
print(x1)

cong = x + x1
print(cong)
x1.shape



[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[0 1 2]
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]


(3,)

In [ ]:
## cho 1 bản np có 150 dòng 5 cột
import numpy as np
from sklearn.model_selection import train_test_split

# 1. Tạo mảng NumPy 150 x 5
np.random.seed(42)  # Đặt seed để kết quả nhất quán
data = np.random.rand(150, 5) * 100  # Tạo mảng ngẫu nhiên, nhân với 100 để tăng giá trị

# 2. Chia cột đầu tiên (chiều cao) thành x và cột cuối cùng (GPA) thành y
x = data[:, 0]  # Cột đầu tiên
y = data[:, -1]  # Cột cuối cùng

# 3. Chia dữ liệu x và y thành train/test (70:30)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# 4. Tạo tập dữ liệu không chồng chéo (loại bỏ giá trị trùng lặp trong x_train)
x_train_unique = np.unique(x_train)




Mảng dữ liệu ban đầu:
[[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404]
 [15.59945203  5.80836122 86.61761458 60.11150117 70.80725778]
 [ 2.05844943 96.99098522 83.24426408 21.23391107 18.18249672]
 [18.34045099 30.4242243  52.47564316 43.19450186 29.12291402]
 [61.18528947 13.94938607 29.21446485 36.63618433 45.60699842]
 [78.51759614 19.96737822 51.42344384 59.24145689  4.64504127]
 [60.75448519 17.05241237  6.5051593  94.88855373 96.56320331]
 [80.83973481 30.46137692  9.7672114  68.42330265 44.01524937]
 [12.20382348 49.51769101  3.43885211 90.93204021 25.87799816]
 [66.25222844 31.17110761 52.00680212 54.67102793 18.48544555]
 [96.95846278 77.51328234 93.94989416 89.48273504 59.78999788]
 [92.1874235   8.84925021 19.59828624  4.52272889 32.53303308]
 [38.86772897 27.13490318 82.87375092 35.67533267 28.09345097]
 [54.26960832 14.0924225  80.21969808  7.45506437 98.68869366]
 [77.22447693 19.87156815  0.55221171 81.54614285 70.68573438]
 [72.9007168  77.12703467  7.4044

In [ ]:
# In kết quả
print("Mảng dữ liệu ban đầu:")
print(data)
print("\nBiến độc lập (x):", x)
print("\nBiến phụ thuộc (y):", y)
print("\nTập x_train:", x_train)
print("\nTập x_test:", x_test)
print("\nTập x_train không chồng chéo:", x_train_unique)

Mảng dữ liệu ban đầu:
[[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404]
 [15.59945203  5.80836122 86.61761458 60.11150117 70.80725778]
 [ 2.05844943 96.99098522 83.24426408 21.23391107 18.18249672]
 [18.34045099 30.4242243  52.47564316 43.19450186 29.12291402]
 [61.18528947 13.94938607 29.21446485 36.63618433 45.60699842]
 [78.51759614 19.96737822 51.42344384 59.24145689  4.64504127]
 [60.75448519 17.05241237  6.5051593  94.88855373 96.56320331]
 [80.83973481 30.46137692  9.7672114  68.42330265 44.01524937]
 [12.20382348 49.51769101  3.43885211 90.93204021 25.87799816]
 [66.25222844 31.17110761 52.00680212 54.67102793 18.48544555]
 [96.95846278 77.51328234 93.94989416 89.48273504 59.78999788]
 [92.1874235   8.84925021 19.59828624  4.52272889 32.53303308]
 [38.86772897 27.13490318 82.87375092 35.67533267 28.09345097]
 [54.26960832 14.0924225  80.21969808  7.45506437 98.68869366]
 [77.22447693 19.87156815  0.55221171 81.54614285 70.68573438]
 [72.9007168  77.12703467  7.4044

In [ ]:
## bài tập về nhà tết
def print_board(board):
    for row in board:
        print(" ".join(str(cell) for cell in row))
    print()

def check_winner(board, player):
    for row in board:
        if all(cell == player for cell in row):
            return True

    for col in range(3):
        if all(board[row][col] == player for row in range(3)):
            return True

    if all(board[i][i] == player for i in range(3)) or all(board[i][2 - i] == player for i in range(3)):
        return True

    return False

def tic_tac_toe():
    board = [[99 for _ in range(3)] for _ in range(3)]
    players = {0: 'O', 1: 'X'}
    turn = 1  # X đi trước

    print("Bài tập tết về nhà - Trò chơi cờ caro")
    print_board(board)

    for _ in range(9):
        while True:
            try:
                row, col = map(int, input(f"Người chơi {players[turn]}, nhập vị trí (hàng, cột): ").split())
                if 0 <= row < 3 and 0 <= col < 3 and board[row][col] == 99:
                    board[row][col] = players[turn]
                    break
                else:
                    print("Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!")
            except ValueError:
                print("Vui lòng nhập hai số cách nhau bằng dấu cách!")

        print_board(board)

        if check_winner(board, players[turn]):
            print(f"Người chơi {players[turn]} thắng!")
            return

        turn = 1 - turn  # Đổi lượt chơi

    print("Hòa! Trò chơi kết thúc.")

tic_tac_toe()


Bài tập tết về nhà - Trò chơi cờ caro
99 99 99
99 99 99
99 99 99

99 99 99
99 99 99
99 X 99

Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
99 99 99
99 99 99
99 X O

Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
99 99 99
99 X 99
99 X O

Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp lệ hoặc đã có người chọn. Hãy thử lại!
Vị trí không hợp